**numpy dizi islemleri**

In [8]:
import numpy as np #numpy kutuphanesini np takma adi ile projeye dahil ediyoruz

In [10]:
dizi=np.full((4,3),5) #4satır 3 sutunluk 5ten oluşan dizi
dizi

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [11]:
#yeni bir numpy dizisi olusturuyoruz
np.array([1,2,3])

array([1, 2, 3])

In [12]:
#oLlusturdugumuz diziyi bir degiskene aktarvryoruz
dizi=np.array(["elma", "erik", "igde"])

In [ ]:
dizi

In [ ]:
dizi=np.array([1,2,3])

In [ ]:
dizi=np.array([1,2,3.14])

In [ ]:
dizi.dtype #dizinin degisken turunu verir. numpy dizilerinde elemanLlarin hepst aynri turdendir

In [ ]:
dizi=np.array([1,2,3.14], dtype=int)

**numpy ile farkli boyutlarda dizi olusturma**

In [ ]:
#bir boyutlu dizi olusturma
birboyut=np.array([1,2,3,4])
#ikt boyutlu dizi olusturma
ikiboyut=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [ ]:
#bir boyutlu dizi olusturma
birboyut=np.array([1,2,3,4])

In [ ]:
#ikt boyutlu dizi olusturma
ikiboyut=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

**numpy yer tutucular**

In [ ]:
np.zeros(7) #7 s1iftrdan olusan tek boyutLlu dizi olusturur

In [ ]:
np.zeros((2,3),dtype=int)#* svtftrdan olusan 2 boyutlu int dizi olusturur

In [ ]:
np.ones(3)

In [ ]:
np.full((4,3),5)#5 sayisindan olusan 2*3 Luk dizi

In [ ]:
np.arange(2,22,5)#baslangic,bitis ve artis degerine gore dizi olusturma

In [ ]:
np.linspace(2,10,num=7) #baslangic¢c ve bitis degeri araliginda belirtilen miktarda esit aralik

In [ ]:
np.random.randint(0,10,5)#@-1@ aral1ginda rastgele 5 sayidan olusan bir boyutlu dizi

In [ ]:
np.random.randint(0,10,(5,2))#@-1@ araliginda 5*2 rastgele sayizdan olusan 2 boyutlu dizi

**diziler ile ilgili islemler**

In [ ]:
#dizilerin eleman sayisinr Ogrenmek t¢in shape komutu kuLllanilir
dizi=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
dizi.shape

In [ ]:
#ndim dizi boyutunu ogrenmek i¢in kullanilir
dizi.ndim

In [ ]:
#s1ze dizidekt toplLam eleman sayirsini gosterir
dizi.size

In [ ]:
dizi.itemsize #dizidekit her bir elemanin bayt cinsinden degerini verir

In [13]:
dizi=np.random.randint(0,30, size=(5,7),dtype=int)
dizi

array([[24, 13,  7, 28, 17, 24,  8],
       [29,  5, 19, 10, 22, 21, 20],
       [17,  0, 15, 12,  9, 28, 15],
       [ 2, 12,  2,  5, 21, 24, 26],
       [26, 15, 25, 14,  5, 11,  4]])